name: YOUDU MESSAGE TEST

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      max-parallel: 15
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]
        php-versions: ["5.6", "7.0", "7.1", "7.2", "7.3"]
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install PHP
        uses: shivammathur/setup-php@master

        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: mbstring, xdebug #optional
          ini-values-csv: "post_max_size=256M, short_open_tag=On" #optional
          coverage: xdebug #optional

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Check PHP Extensions
        run: php -m

      - uses: actions/checkout@v1

      - name: Build Laravel App
        run: |
          cd $HOME
          composer create-project --prefer-dist laravel/laravel webapp

      - name: Install Package
        run: |
          cd $HOME/webapp
          composer config repositories.laravel-youdu-message path /home/runner/work/laravel-youdu-message/*
          composer require "huangdijia/laravel-youdu-message:*@dev"

      - name: Test Artisan
        run: |
          cd $HOME/webapp
          php artisan
